### ISSUE TITLE
Alias for Windows environments

### ISSUE THREAD

**Issue by bheston** [ALMaclaine/replace#22]
This module has a few features that are not in the native Windows command or not syntax-compatible. It would be great to be able to use this cross-platform though. Would you please add a unique alias so it works on Windows (or any other platform where 'replace' resolves to something else)? I haven't found a solution that works well.

**Comment by ALMaclaine** [comment]
How would you suggest accomplishing this?

**Comment by bheston** [comment]
I'm not quite sure how it would work in Node, but I think possibly a dependent package. I am also using [change-case](https://github.com/blakeembrey/change-case) and it has imports for each individual pattern. So I could import `replace` but it would also add `replace-win` or something that could be directly referenced in package.json scripts.

**Comment by ALMaclaine** [comment]
@bheston I don't believe what you are suggesting is possible, globally installed packages are added to path automatically by npm as the name of the package.

**Comment by bheston** [comment]
Yes, that's why change-case has 21 packages, the main one you reference in packages.json and the dependent ones that also get added. I think you would need a second package also published, which essentially functions for back-compat. Is there any other way to reference a package in npm, or is it best to not name it with a reserved or in use word? Are people using this package on Windows? If so I guess only within other scripts that could possibly reference it differently.

**Comment by ALMaclaine** [comment]
Other people do use it with windows, many of the issues filed to this repo are errors from when think people are using this version but they are really using the windows version.

It's unfortunate it conflicts with the windows tool, but I adopted this package so I didn't name it.

I don't plan to publish this package under any other name but if you wish to do so that's fine with me, but I don't think it would solve the issue for the community at large. An alias would be hard to find in search and mostly just benefit the person requesting it. There are other rather popular replace libraries out there if you want a different name.

**Comment by fdendorfer** [comment]
You can use the command via npx to avoid conflict like so `npx replace 'foo' 'bar'`
