### ISSUE TITLE
returns Invalid switch with any options

### ISSUE THREAD

**Issue by dseeker** [ALMaclaine/replace#7]
installed it globally
executed replace -h
got 
```
Invalid switch - -h
No files replaced
```
using Node 8.16 on windows 8

**Comment by ALMaclaine** [comment]
Can you give the full command, I'm using nvm to install 8.16 on Mac and I don't have any issue.

**Comment by kokushkin** [comment]
I've got the same...

> replace 'ActionResultModel' 'ActionResultModel1' swagger.json
Invalid switch - swagger.json
No files replaced
> replace 'ActionResultModel' 'ActionResultModel1' ./swagger.json
Invalid switch - .
No files replaced
> replace 'ActionResultModel' 'ActionResultModel1' .\swagger.json
Invalid switch - .\swagger.json
No files replaced
> replace 'ActionResultModel' 'ActionResultModel1' \swagger.json
Invalid switch - \swagger.json
No files replaced
> replace 'ActionResultModel' 'ActionResultModel1' /swagger.json
Invalid switch - /swagger.json
No files replaced
> replace 'ActionResultModel' 'ActionResultModel1' "swagger.json"
Invalid switch - swagger.json
No files replaced

It makes me crazy!!!

Windows 10, node v10.15.3

**Comment by ALMaclaine** [comment]
I don't believe you two are using npm replace but win32 replace built into cmd... I'm pretty close to certain this is the case because the words 'Invalid switch' and 'No files replaced' are not contained in this project anywhere, but I do get hits related to win32 replace...

**Comment by ALMaclaine** [comment]
Tested it on someones comp, that's the win32 replace:

![image](https://user-images.githubusercontent.com/16461670/61237259-f0916b00-a6ee-11e9-8dae-9c98870f8392.png)

**Comment by kokushkin** [comment]
Omg, you are right! I was blind, thank you!


So, here is my workaround:

"my path">node ./node_modules/replace/bin/replace.js 'ActionResultModel\[ExtendedSelectItemEntity`1\[\]\]' 'ActionResultModel[ExtendedSelectItemEntity_1[]]' ./src/server/helpers/swagger-datasources/swagger.json

This works for me. As you see I have to call replace like this "./node_modules/replace/bin/replace.js" And also wanted to mention I have to escape symbols [, ] like this  \[ ,\] in the first search string because  replace treat it like regular expressions.

So, it works, thank you again, good utility!
